Check capabilities in youki info subcommand
containers/youki pull request #1389
Opened 2022-12-01 10:47 UTC by udzura

Shows supported capabilities that started to be supported in recent kernel release.

At first I tried to call `caps::drop()` actually for each newly added caps, but it required privilege. So I just check these caps from default `CapSet::Bounding`.

2022-12-01 11:01 UTC, YJDoc2 commented
Hey, the CI is failing due to a lint error
Also, is there any related issue/reasoning behind this? Particularly if we are printing the caps, why check only the newly supported ones for printing, why not all that are supported?

2022-12-01 11:35 UTC, udzura commented on crates/youki/src/commands/info.rs
> +        }
It make sense! I'll move it to top level.

2022-12-02 10:27 UTC, YJDoc2 commented
>Also, is there any related issue/reasoning behind this? Particularly if we are printing the caps, why check only the newly supported ones for printing, why not all that are supported?

Hey @udzura apologies for the delay, but can you clarify the above? Apart from that this PR is good to go :+1:

2022-12-02 10:59 UTC, udzura commented
@YJDoc2 

Apologies, just find the questions!

> is there any related issue/reasoning behind this?

No, but if anything, I just encountered the same error as referred in https://github.com/containers/youki/pull/1349 . If `youki info` shows these capabilities, we can fix this kind of errors with much more ease.

> why not all that are supported

I've considered this in advance, but I find there are so many capability flags to show in solo command. Maybe a special flag such as `youki info --capabilities` is required.

2022-12-02 11:55 UTC, YJDoc2 requested changes
Hey, Apologies, can I ask you for two small changes?

2022-12-02 11:55 UTC, YJDoc2 commented on crates/youki/src/commands/info.rs
> +        "unsupported"
Can we  have either `supported` and `unsupported` or `available` and `unavailable`? I thought on it and it feels it'd be better if we have one of these two

2022-12-02 11:55 UTC, YJDoc2 commented on crates/youki/src/commands/info.rs
> +fn get_cap_supported(caps: &caps::CapsHashSet, cap: caps::Capability) -> &'static str {
can we rename this to `is_cap_supported` or`is_cap_available`  depending on how we are wording the output?

2022-12-05 14:45 UTC, YJDoc2 commented
Hey @udzura , would it be possible for you to make the changes? If you are busy, I'd be happy to push a commit in this PR and merge. Please let me know :)

2022-12-07 05:11 UTC, udzura commented
@YJDoc2 Very sorry for being late! I've applied suggestions.

2022-12-07 06:11 UTC, YJDoc2 approved these changes
lgtm :+1: Thanks for your contribution!

2022-12-07 06:12 UTC, merged