Correctly handle the rootfs path with bundle
containers/youki pull request #153
Opened 2021-07-21 07:04 UTC by yihuaf

The rootfs path is not correctly handled. The safe guarded version of
the spec doesn't contain the canonicalized rootfs with the bundle path.
The solution here is to save the rootfs path with bundle path into the
safe guarded version of the spec.

fix #152

2021-07-21 18:06 UTC, yihuaf commented
> @yihuaf
> Can I ask you to add unit tests for `save` and `canonicalize_rootfs`?

Will do.

2021-07-22 02:37 UTC, utam0k approved these changes

2021-07-22 02:39 UTC, utam0k requested changes
The CI is down, please fix it.

2021-07-22 03:51 UTC, utam0k approved these changes

2021-07-22 03:53 UTC, merged