checkpoint: Add the missing options
containers/youki pull request #1613
Opened 2023-03-03 15:56 UTC by c3d

Add the missing command-line options as documented for runc: https://github.com/opencontainers/runc/blob/main/man/runc-checkpoint.8.md

(This does not mean that they are necessarily implemented)

@adrianreber In case you need to sync the options for this command.

2023-03-03 15:57 UTC, c3d commented
@adrianreber For context, this is part of the work I am doing on `ociplex`, and attempt to restore `podman` compatibility for Kata Containers using Youki as an in-between, see https://github.com/c3d/youki/tree/ociplex.

2023-03-03 15:58 UTC, c3d commented on crates/liboci-cli/src/checkpoint.rs
> +    pub status_fd: Option<u32>, // TODO: Is u32 the right type?
For what it's worth, I am not sure how file descriptors should be passed around in that context.

2023-03-03 17:46 UTC, adrianreber commented
Not sure this is a good idea. Podman tries to figure out certain features of crun and runc by parsing the help output. The expectation is, that if it is listed in the help output it is supported.

In the case of youki it is not really important as checkpoint is still hidden behind `checkpointt`.

2023-03-03 21:51 UTC, c3d commented
> Not sure this is a good idea. Podman tries to figure out certain features of crun and runc by parsing the help output. The expectation is, that if it is listed in the help output it is supported.
> 
> In the case of youki it is not really important as checkpoint is still hidden behind `checkpointt`.

I was not aware of this behaviour of `podman`. That's weird 😄 . Well, I need these changes on my branch, feel free to pick them up if/when you implement that. I'll also figure out a way to have this be different for `ociplex` and `youki`.

2023-03-04 09:42 UTC, adrianreber commented
> > Not sure this is a good idea. Podman tries to figure out certain features of crun and runc by parsing the help output. The expectation is, that if it is listed in the help output it is supported.
> > In the case of youki it is not really important as checkpoint is still hidden behind `checkpointt`.
> 
> I was not aware of this behaviour of `podman`. That's weird smile . Well, I need these changes on my branch, feel free to pick them up if/when you implement that. I'll also figure out a way to have this be different for `ociplex` and `youki`.

It is only during restore: https://github.com/containers/podman/blob/main/pkg/checkpoint/crutils/checkpoint_restore_utils.go#L229

2023-03-06 10:12 UTC, c3d commented
@adrianreber OK, I understand your constraints. In any case, the changes in this PR are not for immediate consumption. It's more "If you need to implement this or that option, feel free to grab it from this branch". I will try to maintain two parallel branches:

* [The oci-changes branch](https://github.com/c3d/youki/tree/oci-changes), where I'll try to keep only the OCI command-line interface changes

* [The ociplex branch](https://github.com/c3d/youki/tree/ociplex) where we are developing an OCI multiplexer that leverages youki's command-line parsing, the primary goal being to build a bridge between `podman` and `shimv2`-only runtimes like Kata Containers v2 and later.

I'll try to reorder and cleanup the commits in these branches to rebase `ociplex` on `oci-changes`. In case there is no negative impact of adding the missing options. It's really your call if and when you want to do that.

2023-03-07 02:35 UTC, utam0k commented
> Not sure this is a good idea. Podman tries to figure out certain features of crun and runc by parsing the help output. The expectation is, that if it is listed in the help output it is supported.
> 
> In the case of youki it is not really important as checkpoint is still hidden behind `checkpointt`.

BTW, podman should use the feature command to verify the futures of the oci runtimes
https://github.com/opencontainers/runtime-spec/pull/1130

2023-03-07 09:57 UTC, c3d commented
> On 7 Mar 2023, at 03:36, Toru Komatsu ***@***.***> wrote:
> 
> 
> Not sure this is a good idea. Podman tries to figure out certain features of crun and runc by parsing the help output. The expectation is, that if it is listed in the help output it is supported.
> In the case of youki it is not really important as checkpoint is still hidden behind checkpointt.
> BTW, podman should use the feature command to verify the futures of the oci runtimes
> opencontainers/runtime-spec#1130


Interesting. I was not aware of this command, and it’s not implemented in Youki yet, but it's tracked.

https://github.com/containers/youki/issues/815

2023-03-07 23:02 UTC, utam0k commented on crates/liboci-cli/src/features.rs
> +use clap::Parser;
May I ask you to update the README for liboci-cli?
https://github.com/containers/youki/tree/main/crates/liboci-cli

2023-03-07 23:05 UTC, utam0k requested changes
I apologize for the inconvenience, but for commands that are not yet implemented, you should make it clear in the prefix in the comment section of each option.
Then they should appear in the help command.

2023-03-08 08:53 UTC, c3d commented
@utam0k Not an inconvenience at all. Thanks for pointing that out, I'll work on it.

2024-05-20 04:42 UTC, yihuaf commented
Given this PR is stale for more than a year, I will close this. Please re-open when needed.

2024-05-20 04:42 UTC, closed without merging