Add support to Intel RDT.
containers/youki pull request #1822
Opened 2023-04-17 13:29 UTC by ipuustin

Add support to Intel RDT.

Fixes: #443.

This PR implements also the suggested additions to OCI runtime spec here: https://github.com/opencontainers/runtime-spec/pull/1196

2023-04-18 12:05 UTC, utam0k commented
@ipuustin Thanks for your PR. Since I need some time to learn Interl RDT, I'll check this next weekend.

2023-04-21 10:40 UTC, ipuustin commented
Note that this PR is needed to oci-spec-rs in order for the `closID` spec setting to have any effect: https://github.com/containers/oci-spec-rs/pull/128

2023-04-23 12:02 UTC, utam0k commented on crates/libcontainer/Cargo.toml
> +lazy_static = "1.4.0"
Since we are using `once_cell`, please use it instead of `lazy_static` :pray:

2023-04-23 12:18 UTC, utam0k commented on crates/libcontainer/src/process/container_main_process.rs
> +    let mut need_to_clean_up_intel_rdt_subdirectory: bool = false;
nits
```suggestion
    let mut need_to_clean_up_intel_rdt_subdirectory = false;
```

2023-04-23 12:19 UTC, utam0k requested changes
Wait for updating oci-spec-rs

2023-04-24 11:29 UTC, ipuustin commented
@utam0k Thanks for reviewing! I implemented the suggested changes.

2023-04-24 11:56 UTC, utam0k commented
@ipuustin Thanks 😍 May I ask you to give me the instructions to confirm the behavior you have implemented?

2023-04-24 12:35 UTC, ipuustin commented
The documentation of the kernel resctrl interface (which this PR uses) is here: https://docs.kernel.org/x86/resctrl.html

Briefly, you mount the resctrl filesystem (`mount -t resctrl resctrl /sys/fs/resctrl`) and then you should be set. The code doesn't really concern itself with what the resctrl actually does: it just maps the OCI config values to the `/sys/fs/resctrl/<container_id>/schemata` file, with the instructions speficied in the OCI spec. In case you specify the `closID` value, the changes are done to `/sys/fs/resctrl/<clos_id>/schemata` file instead (if the directory doesn't exist already, otherwise the proposed changes will just be compared with the existing schemata file).

Which changes can you do to the schemata files depend on the computer system you have in use. A good approximation would be to see what the kernel has prepopulated to the schemata files and try to modify those values.

The OCI config spec has this example for the config.json file:

    "linux": {
        "intelRdt": {
            "closID": "guaranteed_group",
            "l3CacheSchema": "L3:0=7f0;1=1f",
            "memBwSchema": "MB:0=20;1=70"
        }
    }

2023-04-24 13:07 UTC, ipuustin commented
Rebased to fix conflict in Cargo.lock.

2023-04-27 03:12 UTC, utam0k approved these changes
:100:

2023-04-27 03:12 UTC, merged