Make optional types optional
containers/youki pull request #183
Opened 2021-08-04 14:11 UTC by saschagrunert

This adds a few missing types and synchronizes them with the
implementation in containrs. Optional types are now not required any
more which means that all necessary code paths in youki needs to be
adapted as well.

2021-08-04 14:11 UTC, saschagrunert commented
Ooof, sorry for the huge PR.

2021-08-04 15:26 UTC, utam0k commented on src/cgroups/v1/blkio.rs
> +            .context("no throttle_read_bps_device in linux blkio")?
This is something that should be resolved separately from this PR, but I think there needs to be an implementation for when the config is missing.
I will compile a list of missing implementations of this kind and put them in an issue at a later date.

2021-08-04 15:31 UTC, utam0k commented on src/cgroups/v1/blkio.rs
> +            .context("no throttle_read_bps_device in linux blkio")?
https://github.com/containers/youki/issues/184

2021-08-04 15:47 UTC, utam0k requested changes
Can I ask you to check the default test in the runtime-tools integration test, because it seems to take infinite time and the test is not progressing?
I can check it tomorrow night on my end.

2021-08-05 10:15 UTC, saschagrunert commented
Yeah the issue is now that with making the types optional, we also have to make the code paths in youki optional. Right now the integrations tests will fail because for example:
```
[DEBUG src/container/builder_impl.rs:88] 2021-08-05T12:11:04.943893124+02:00 failed to run container_init: Failed to prepare rootfs

Caused by:
    no mount_label in spec
```

2021-08-05 14:32 UTC, utam0k commented
@saschagrunert Thanks for your report. I have started to fix it based on your report, but I need more time, so please wait a few days.
https://github.com/saschagrunert/youki/pull/1

2021-08-06 07:36 UTC, saschagrunert commented
> @saschagrunert Thanks for your report. I have started to fix it based on your report, but I need more time, so please wait a few days.
> [saschagrunert#1](https://github.com/saschagrunert/youki/pull/1)

Oh wow, cool thank you! I was wondering if making it optional is the right approach, but when it comes to serializing then I still think that having them as `Option` types is the correct way to represent the data.

2021-08-09 10:37 UTC, utam0k commented
@saschagrunert 
Sorry, I missed a few things and it wasn't working. I sent out a PR to fix it.
https://github.com/saschagrunert/youki/pull/2

2021-08-09 13:43 UTC, utam0k commented
Hmm, I'll try exactly that in my forked repository later.

2021-08-10 07:28 UTC, saschagrunert commented
Gave it another rebase because of the conflicts

2021-08-10 14:13 UTC, utam0k commented
@saschagrunert 
I'm sorry for repeating myself. I'm sure this time!
https://github.com/saschagrunert/youki/pull/3

2021-08-11 01:04 UTC, utam0k commented
@saschagrunert 
I think my patch has been merged, but it is not reflected in this PR. Hmmm... do you have any idea what might be causing this?

2021-08-11 07:05 UTC, saschagrunert commented
> @saschagrunert
> I think my patch has been merged, but it is not reflected in this PR. Hmmm... do you have any idea what might be causing this?

GitHub had some issues yesterday, I'll re push the merge commit.

2021-08-11 09:55 UTC, utam0k approved these changes
Thasnk!

2021-08-11 09:56 UTC, merged

2021-08-11 09:56 UTC, saschagrunert commented
I think we can now transfer the source code into https://github.com/containers/oci-spec-rs, do you wanna take care of that?

2021-08-11 10:30 UTC, utam0k commented
> I think we can now transfer the source code into [containers/oci-spec-rs](https://github.com/containers/oci-spec-rs), do you wanna take care of that?

Yes, I will try it around this weekend.