Refactor the lifecycle test
containers/youki pull request #1868
Opened 2023-05-01 20:44 UTC by yihuaf

As previously discussed, the `TestResult` is meant to be used in the test cases and not utility functions. Before this PR, the lifecycle test calls other tests using `TestResult` which is not inline with our intention. This PR fix this by refactoring all tests to not call other tests in test cases.

2023-05-05 05:07 UTC, YJDoc2 requested changes
Hey, overall its fine, just a few nits.

As you had said this makes much more sense that what we currently have. Thanks for taking initiative and making this change!

2023-05-05 05:07 UTC, YJDoc2 commented on tests/rust-integration-tests/integration_test/src/tests/lifecycle/container_create.rs
> +                let _ = delete::delete(&self.project_path, &id);
This is duplicated in both arms, so we should extract it before the match.

2023-05-05 05:07 UTC, YJDoc2 commented on tests/rust-integration-tests/integration_test/src/tests/lifecycle/container_create.rs
> +            )),
Maybe we should bubble the actual error up too (through the `anyhow!`), so if this ever fails, we can get the error

2023-05-05 19:03 UTC, yihuaf commented
@YJDoc2 PTAL

2023-05-06 06:04 UTC, YJDoc2 approved these changes
lgtm :+1:

2023-05-06 06:05 UTC, merged