Implemented more `thiserror` for libcontainer (Part 2)
containers/youki pull request #1881
Opened 2023-05-04 19:31 UTC by yihuaf

Implemented more `thiserror` for the libcontainer. This PR covers most of the low hanging fruits with smaller crates. Note, I decided to add a new syscall error wrapper that wraps the `nix::Error`, `std::io::Error`, and our own syscall crate. This aims to simplify where we call syscalls from 3 different sources and can simplify/unify many errors.

2023-05-06 02:31 UTC, utam0k approved these changes

2023-05-06 02:32 UTC, utam0k commented
@squili 
Could you review this PR?

2023-05-06 09:06 UTC, squili requested changes
Looks great - just a minor nitpick

2023-05-06 09:06 UTC, squili commented on crates/libcontainer/src/notify_socket.rs
> +    #[error("failed to chdir when create notify socket")]
maybe `"failed to chdir while creating notify socket"` would be more clear

2023-05-08 03:16 UTC, squili approved these changes

2023-05-08 03:24 UTC, merged