Add support for rsvd hugetlb cgroup
containers/youki pull request #2719
Opened 2024-03-04 04:25 UTC by omprakaash

Adds support for rsvg hugetlb cgroup. More Info on why this is necessary: https://github.com/opencontainers/runtime-spec/pull/1116.

2024-03-05 18:23 UTC, omprakaash commented
I can also open up a PR in oci-spec-rs if necessary to update info about huge-tlb limits.

2024-03-06 12:20 UTC, utam0k commented
> I can also open up a PR in oci-spec-rs if necessary to update info about huge-tlb limits.

Let's do it.

2024-03-09 19:54 UTC, omprakaash commented
Hey, sorry for the delay. Opened up a corresponding PR in oci-spec-rs repo as well.

2024-03-13 12:05 UTC, utam0k commented
@omprakaash May I ask you to add a e2e test?
https://containers.github.io/youki/developer/e2e/rust_oci_test.html

2024-03-13 13:53 UTC, omprakaash commented
Oh yes ! Will add one.

2024-03-18 06:20 UTC, YJDoc2 commented
Hey, do we need a oci-spec release and update its version in this PR ?

2024-04-01 00:01 UTC, utam0k commented
@omprakaash friendly remind ;)

2024-04-01 00:02 UTC, utam0k commented
> Hey, do we need a oci-spec release and update its version in this PR ?

If need, I can do it.

2024-04-01 06:42 UTC, utam0k commented on tests/contest/contest/src/tests/tlb/tlb_test.rs
👍

2024-04-01 07:21 UTC, utam0k requested changes

2024-04-01 07:21 UTC, utam0k commented on crates/libcgroups/src/v1/hugetlb.rs
> +        let mut rsvd = ".rsvd";
How about this?
```suggestion
        let mut file_prefix= format!("hugetlb.{page_size}.rsvd");
```

2024-04-01 07:21 UTC, utam0k commented on crates/libcgroups/src/v2/hugetlb.rs
> +
```suggestion
        common::write_cgroup_file(
            root_path.join(format!("hugetlb.{}.rsvd.max", hugetlb.page_size())),
            hugetlb.limit(),
        )?;

```

2024-04-01 07:21 UTC, utam0k commented on crates/libcgroups/src/v2/hugetlb.rs
> +        let mut rsvd = ".rsvd";
Same as comment in cgroup v1.

2024-04-02 01:18 UTC, omprakaash commented on crates/libcgroups/src/v1/hugetlb.rs
> +use std::{collections::HashMap, num::ParseIntError, path::Path};
Oh, cargo fmt seems to switch the order around .

2024-04-02 01:18 UTC, omprakaash commented on crates/libcgroups/src/v1/hugetlb.rs
> +        let mut rsvd = ".rsvd";
Oh that is better, will change it.

2024-04-02 12:02 UTC, utam0k commented
@omprakaash It looks like the unit test failed. Please check it
https://github.com/containers/youki/actions/runs/8515994057/job/23342405969?pr=2719

2024-04-03 02:00 UTC, omprakaash commented on crates/libcgroups/src/v1/hugetlb.rs
> +
Oh, I ignored the result because the desired behavior was falling back to just writing to the non-rsvd file if the rsvd file was not present.

2024-04-03 02:03 UTC, omprakaash commented
Oh that is because the functions fails if the write to the new rsvd file fails. If rsvd is not supported, I think we should fallback to just writing to the non-rsvd file (https://github.com/opencontainers/runtime-spec/pull/1116/files). I left a follow up comment in the code review - [review](https://github.com/containers/youki/pull/2719#discussion_r1546027138)

2024-04-03 12:44 UTC, utam0k commented
> Oh that is because the functions fails if the write to the new rsvd file fails. If rsvd is not supported, I think we should fallback to just writing to the non-rsvd file (https://github.com/opencontainers/runtime-spec/pull/1116/files). I left a follow up comment in the code review - [review](https://github.com/containers/youki/pull/2719#discussion_r1546027138)

These unit tests use temporary dirs(`/tmp`). It means we don't use actual cgroup fs. You can put any file to simulate support rsvd in a temporary dir.

2024-04-04 03:34 UTC, omprakaash commented
Hey, sorry I might be misunderstanding, but that is what the newly added tests do (eg: `test_set_rsvd_hugetlb()` ). So this test is testing that the application of hugetlb stats does not error out if rsvd-hugetlb file is not present.

2024-04-04 11:50 UTC, utam0k commented
@omprakaash 
Oh, I was wrong. I understood.

But there are possibilities of errors except for what you expect when writing the cgroup file, so we can't ignore this result.
> Oh, I ignored the result because the desired behavior was falling back to just writing to the non-rsvd file if the rsvd file was not present.

How about checking if the rvsd is support before writing rvsd's cgroup file?
https://github.com/omprakaash/youki/blob/f2bf35c0b4244bf4d1a73e56c85de3c7b3b11def/crates/libcgroups/src/v2/hugetlb.rs#L109-L112

2024-04-07 04:09 UTC, omprakaash commented
Gotcha, changed it so that we first check if the rsvd file exists before attempting to write into it.

2024-04-07 05:26 UTC, utam0k approved these changes
LGTM 👍 Thanks, @omprakaash

2024-04-07 05:34 UTC, merged