Remove chdir
containers/youki pull request #2777
Opened 2024-05-01 23:47 UTC by Mossaka

Remove unnecessary `chdir` in container `init` and `start`, the invokes seem not necessary.

Pending comments from https://github.com/containers/youki/issues/2772#issuecomment-2088446225 and will close issue #2772

2024-05-02 14:46 UTC, YJDoc2 commented
Hey, the CI is failing because cross now requires rust 1.77.2 and we use 1.77.1. Have opened https://github.com/containers/youki/pull/2779 which should fix all the CI running issues, so once that is merged, you can rebase on that.

2024-05-02 14:55 UTC, YJDoc2 commented
It is merged, so you can go ahead :+1:

2024-05-02 19:10 UTC, Mossaka commented
It seems like the integration test failed. I am not able to tell if it's related to my changes

2024-05-02 21:12 UTC, utam0k requested changes
Please wait until we investigat this as it could break pseudo terminal.

2024-05-02 21:15 UTC, Mossaka commented
> Please wait until we investigat this as it could break pseudo terminal.

Sounds good. That's why I made this PR a draft one until we figure out if it's not breaking existing functionality of youki.

2024-05-02 21:17 UTC, jprendes commented
3 tests failed, all related to setting up tty.

```
        Error: exec process failed with error error in executing process : failed to setup tty
        : unknown
--- FAIL: TestContainerPTY (0.15s)
```

```
        Error: exec process failed with error error in executing process : failed to setup tty
        : unknown
--- FAIL: TestTaskResize (0.08s)
```

```
    container_test.go:1890: OCI runtime exec failed: runc did not terminate successfully: exit status 255: exec failed : exec process failed with error error in executing process : failed to setup tty
        : unknown
--- FAIL: TestContainerExecLargeOutputWithTTY (0.13s)
```

2024-05-03 00:56 UTC, utam0k commented
I was worried about catching it on the test, but it looks like they were testing it! I want to thank our past selves.

2024-05-03 13:09 UTC, utam0k commented
Sorry, but I've created another PR to fix it.
https://github.com/containers/youki/pull/2780

2024-05-03 13:09 UTC, closed without merging