Add test code linux_cgroups_devices
containers/youki pull request #3000
Opened 2024-11-21 22:41 UTC by sat0ken

This implements the linux_cgroups_devices validation in https://github.com/youki-dev/youki/issues/361

2024-11-23 15:16 UTC, YJDoc2 commented
Hey @sat0ken thanks for the PR! I missed replying to your message on the issue, but I would have requested you to wait a bit before opening the PR. There is another PR which makes some refactor on test code, and that has been waiting for sometime to get merged. I plan to get that merged first and then ask authors of open test PRs to rebase on the main for the changes. I'll ping you once that is done, so you can rebase, and then I'll review this one.

I also request you to hold off on the relative_devices PR till that is done, but I have assigned that to you on the issue.

2024-11-24 06:14 UTC, sat0ken commented
@YJDoc2 OK! I got it. thank you.

2024-11-27 05:06 UTC, YJDoc2 commented
Hey @sat0ken , that PR is merged, so you can rebase this once and also work on the relative devices. However, in future I will request to only work on one PR at a time :sweat_smile:

2024-11-27 11:42 UTC, sat0ken commented
@YJDoc2 Thank you for notify.

>  However, in future I will request to only work on one PR at a time 😅
I'm sorry, I'll be careful from now on.

2024-12-02 12:12 UTC, utam0k commented
> I'm sorry, I'll be careful from now on.

There is no need to apologize; @YJDoc2 has just suggested a smooth way to develop. I often make this mistake myself.

2024-12-03 13:34 UTC, YJDoc2 requested changes
Hey, there are some changes needed. Also can you confirm this is impl of `linux_cgroups_devices` and not `linux_cgroups_relative_devices` ?

2024-12-03 13:34 UTC, YJDoc2 commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +        .access(access)
Why are we setting access twice? Is one of them supposed to be allow instead?

2024-12-03 13:34 UTC, YJDoc2 commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +        linux_device_build(true, LinuxDeviceType::B, 10, 200, "r".to_string()),
If we are setting `true` in all three, we can instead directly set true in the function, and not pass the parameter at all.

2024-12-03 13:34 UTC, YJDoc2 commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +        TestResult::Passed
We have to check container is created AND the devices are setup correctly using a function like [this](https://github.com/opencontainers/runtime-tools/blob/master/validation/util/linux_resources_devices.go#L13) .
See the `runtimeOutsideValidate` call in the original test [here](https://github.com/opencontainers/runtime-tools/blob/master/validation/linux_cgroups_devices/linux_cgroups_devices.go#L24) , where we call the above function to validate the devices.

2024-12-03 13:34 UTC, YJDoc2 commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +    test_result
This is no-op, we can simply return the `test_outside_container` here as the last statement in the function block

2024-12-03 13:34 UTC, YJDoc2 commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +                .cgroups_path(Path::new("/runtime-test").join(cgroup_name))
I think this is incorrect. For absolute cgroups path, it should be single level at root like `/cgrouptest` . Joining another path here would make it relative.

2024-12-03 13:36 UTC, YJDoc2 commented
> I'm sorry, I'll be careful from now on.

Hey, as @utam0k mentioned, no need to apologize, in fact I apologies if my comment seemed too harsh. We haven't mentioned this in the main issue as well, which we should, and I was suggesting that so it would be easier for us to  review the PRs. :sweat_smile: :smile:

2024-12-04 05:30 UTC, sat0ken commented
@utam0k @YJDoc2 

Thank you review and kind comment!

>I apologies if my comment seemed too harsh.

Don't worry about it.
I'm newbie about Rust and container, but I enjoying to contribute to youki. I will fix the code, wait please.

2025-01-19 01:59 UTC, sat0ken commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +        .access(access)
It's my mistake. I fixed it.

https://github.com/youki-dev/youki/pull/3000/commits/0ea31ff49b399e79ac9165f159968b95c75e7f1d

2025-01-19 01:59 UTC, sat0ken commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +        linux_device_build(true, LinuxDeviceType::B, 10, 200, "r".to_string()),
I fixed it.

https://github.com/youki-dev/youki/commit/0ea31ff49b399e79ac9165f159968b95c75e7f1d

2025-01-19 02:03 UTC, sat0ken commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +        TestResult::Passed
I fixed about like original test, read devices.list file, and compare to spec. 

https://github.com/youki-dev/youki/pull/3000/commits/dc5a1c16b0bb7db36df363c2c8a31fce2dca1bc5

2025-01-19 02:04 UTC, sat0ken commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +    test_result
I fixed it.

https://github.com/youki-dev/youki/commit/dc5a1c16b0bb7db36df363c2c8a31fce2dca1bc5

2025-01-19 02:17 UTC, sat0ken commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +                .cgroups_path(Path::new("/runtime-test").join(cgroup_name))
Becouse, I check `linux_cgroups_blkio` test code, this code look like join path.
For absolute cgroups test, Shouldn't we join path?

https://github.com/youki-dev/youki/blob/main/tests/contest/contest/src/tests/cgroups/blkio.rs#L95

2025-01-19 02:21 UTC, sat0ken commented
@YJDoc2 

I fixed some code, could you please check it?
I don't know why failed e2e test and I have [question](https://github.com/youki-dev/youki/pull/3000#discussion_r1921351201).

2025-01-22 16:14 UTC, sat0ken commented
@YJDoc2 
There's no need to apologies. Please take good care of yourself. Anytime is ok.

2025-09-07 06:39 UTC, utam0k commented
@sat0ken I'll start the review. But please rebase from the main branch before starting to review.

2025-09-10 12:58 UTC, sat0ken commented
@utam0k 
Thank you for review. I did rebase from main.

2025-09-17 12:17 UTC, utam0k commented
> @utam0k Thank you for review. I did rebase from main.

It looks like you made a mistake when rebasing.

2025-09-20 15:03 UTC, sat0ken commented
> It looks like you made a mistake when rebasing.

OMG. Sorry, I fix it.

2025-10-17 00:23 UTC, utam0k requested changes

2025-10-17 00:23 UTC, utam0k commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +                // ignore invalid format
Why can we ignore invalid formats?

2025-10-17 00:23 UTC, utam0k commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +            for linux_device in linux_devices.clone() {
Do we really need `clone()`?

2025-10-17 00:23 UTC, utam0k commented on tests/contest/contest/src/tests/cgroups/devices.rs
> +                minor.unwrap(),
If `*` comes into this logic, I guess it will cause panic.

2026-06-20 23:05 UTC, saku3 commented
Thank you for your contribution.

As mentioned in #3285, cgroup v1 is no longer maintained. Unless there is a specific reason to continue working on cgroup v1, new cgroup-related test work should focus on cgroup v2.

If you would like to work on cgroup v2 tests, please see #3605

For this reason, I’m going to close this PR.

2026-06-20 23:05 UTC, closed without merging