Add shell completion
containers/youki pull request #515
Opened 2021-12-04 08:46 UTC by creepinson

## Changes

I added shell completion for zsh, bash or any other shell that clap_generate supports.

This is how I used it in my setup with zsh:

```bash
youki completion -g zsh > ~/.zfunc/youki.zsh
```

2021-12-04 08:58 UTC, utam0k commented
@creepinson 
Hi! Thanks for your suggestion. But you may  have forgotten running format.

2021-12-04 09:01 UTC, creepinson commented
You're right, I had used vscode's rust-analyzer formatter assuming that would work fine.

2021-12-04 14:18 UTC, Furisto commented on crates/youki/src/commands/completion.rs
> +#[derive(Debug, Parser)]
youki -h currently does not have a description for this command

```suggestion
Generate scripts for shell completion
#[derive(Debug, Parser)]
```

2021-12-04 14:19 UTC, utam0k commented on crates/youki/src/commands/completion.rs
> +pub fn print_completions<G: Generator>(gen: G, app: &mut App) -> Result<(), anyhow::Error> {
How about using `anyhow::Result`?

2021-12-04 14:54 UTC, Furisto requested changes

2021-12-04 14:54 UTC, Furisto commented on crates/youki/src/main.rs
> +        }
```suggestion
        SubCommand::Completion(completion) => {
            commands::completion::completion(completion, &mut app)
        }
```

2021-12-04 14:54 UTC, Furisto commented on crates/youki/src/commands/completion.rs
> +}
```suggestion
pub struct Completion {
    #[clap(long = "shell", short = 's', arg_enum)]
    pub shell: Shell,
}
```

2021-12-04 14:54 UTC, Furisto commented on crates/youki/src/main.rs
> +    Completion(commands::completion::CompletionParser),
```suggestion
    Completion(completion::Completion),
```

2021-12-04 14:54 UTC, Furisto commented on crates/youki/src/commands/completion.rs
> +}
```suggestion
pub fn print_completions(args: Completion, app: &mut App) -> Result<()> {
    generate(args.shell, app, app.get_name().to_string(), &mut io::stdout());

    Ok(())
}
```

2021-12-04 14:57 UTC, Furisto commented
Minor stuff, the style should be consistent with the other commands.

2021-12-05 02:38 UTC, creepinson commented
Looks like I messed up the order of the comment and the `#[derive(Debug, Parser)]` line next to the struct, although `cargo fmt --all --check` is successful. Otherwise I believe I made the requested changes.

2021-12-05 11:56 UTC, utam0k approved these changes
Thanks!

2021-12-05 13:38 UTC, Furisto approved these changes

2021-12-05 13:38 UTC, Furisto commented
Great!

2021-12-05 13:39 UTC, merged