Draft: Suppport executing wasm workloads with wasmer
containers/youki pull request #548
Opened 2021-12-19 16:53 UTC by Furisto

2021-12-21 18:03 UTC, tsturzl commented
This is really interesting. I'm wondering how you plan to distinguish between a container and a wasm workload, and how a high level runtime might integrate with this. This could be a really interesting alternative to something like Krustlet which could allow you to run wasm and container workloads on the same kubelet, whereas krustlet only supports wasm workloads on the hosts running it.

2021-12-22 23:29 UTC, Furisto commented
@tsturzl This is based on the [compat](https://github.com/solo-io/wasm/blob/master/spec/spec-compat.md) variant of the Wasm Image Specification. The config.json needs to have an annotation of either run.oci.handler or module.wasm.image/variant in order for us to detect that a wasm workload has be run. The linked spec also describes how to build an image that is compliant with the Wasm Image spec. Here is an [example](https://github.com/second-state/wasmedge-containers-examples/blob/main/crio/README.md) of how you can use it with CRI-O.

2022-01-05 02:39 UTC, tsturzl commented
I will also review in addition to @utam0k. This is a pretty big change so it's probably good to have a few eyes on it. This is awesome work though.

2022-01-05 05:39 UTC, tsturzl requested changes
First of all, this is really cool stuff, and it's awesome that you took the time and initiative to do this work. So thank you for that. I'm not entirely on board with using dynamic dispatch here. I think perhaps I'd consider refactoring to get rid of the CompositeExecutor and opt for a ExecutorManager that doesn't need to satisfy the Executor trait. This ExecutorManager would instead statically dispatch hard coded Executors with a match block, and therefore only instantiate and allocate the Executor that is determined is actually needed, you can probably still use `can_handle` just don't have `can_handle` require a reference to `self`, in fact you can probably completely avoid the need to instantiate Executors and have all of the trait methods be static (no ref to self) just like we currently do with cgroups controllers, self is never used anyway and there's no point in instantiating then either.

Let me know what you think of this. It's possible there's an argument for dynamic dispatch that I'm missing, or maybe others prefer this approach also. Even if we decide dynamic dispatch is best I'd say the CompositeExecutor should probably just be an ExecutorManager that doesn't satisfy the Executor trait and all Executors should just be static structs that never need to be instantiated.

2022-01-05 05:39 UTC, tsturzl commented on crates/libcontainer/src/workload/mod.rs
> +                .can_handle(spec)
And of course, I'm not demanding the change, but perhaps it's worth the conversation. Maybe there's things I'm not considering or overlooking here, or maybe others find the dynamic dispatch approach to be nicer also.

2022-01-05 05:39 UTC, tsturzl commented on crates/libcontainer/src/workload/mod.rs
> +impl Executor for CompositeExecutor {
What's the benefit for having a CompositeExecutor? It seems the major benefit for an Executor is that is creates a common interface for Executors, could this maybe just be a ExecutorManager that doesn't need to satisfy `Executor`? I don't imagine we'll ever need the `name` function here, and that's just dead code.

2022-01-05 05:39 UTC, tsturzl commented on crates/libcontainer/src/workload/wasmer.rs
> +    fn can_handle(&self, spec: &Spec) -> Result<bool> {
In all the instances of `can_handle` Result isn't ever really needed, and always returns `Ok`. This seems like unnecessary indirection.

2022-01-05 05:39 UTC, tsturzl commented on crates/libcontainer/src/workload/mod.rs
> +    fn exec(&self, spec: &Spec) -> Result<()>;
Do any of the functions for Executor actually need a reference to `self`? The CompositeExecutor is the only one that uses it, and it probably doesn't even need to satisfy this trait. If none of the Executors needed a `&self`, you'd also avoid the need to ever instantiate Executors, which aside from the CompositeExecutor are all empty structs.

2022-01-05 05:43 UTC, tsturzl commented on crates/libcontainer/src/workload/mod.rs
> +        for executor in &self.executors {
Mind you this loop may go away if we agree against dynamic dispatch.

2022-01-05 05:48 UTC, tsturzl commented on docs/src/user/webassembly.md
> +```json
Overall, I'd say it's probably worth providing a couple of links to helpful references here. Like the links I posted in my comment, and some of the references you linked in the PR comments.

2022-01-05 05:49 UTC, tsturzl commented
@utam0k Could you also look through my review and provide your input?

2022-01-08 07:19 UTC, utam0k commented
@Furisto 
As this feature is very interesting, I think that this should be written in README.md. Can I ask you to write?

2022-01-08 07:40 UTC, utam0k commented
> First of all this is really cool stuff, and it's awesome that you took the time and initiative to do this work. So thank you for that. I'm not entirely on board with using dynamic dispatch here. I think perhaps I'd consider refactoring to get rid of the `CompositeExecutor` and opt for a `ExecutorManager` that doesn't need to satisfy the `Executor` trait. This `ExecutorManager` would instead select hard coded `Executors` with a `match` block, and therefore only instantiate and allocate the `Executor` that is determined is actually needed. You can probably still use `can_handle` just don't have `can_handle` require a reference to `self`, in fact you can probably completely avoid the need to instantiate `Executors` and have all of the trait methods be static (no ref to self) just like we currently do with cgroups controllers, self is never used anyway (other than `CompositeExecutor`) and there's no point in instantiating these empty structs.
> 
> Let me know what you think of this. It's possible there's an argument for dynamic dispatch that I'm missing, or maybe others prefer that approach also. Even if we were to decide dynamic dispatch is best I'd say the `CompositeExecutor` should probably just be an `ExecutorManager` that doesn't satisfy the `Executor` trait and all `Executors` should just be static structs that never need to be instantiated.

@Furisto 
First of all, now this design is not bad at all. But I agree with @tsturzl's option because perhaps executor will only increase the number of types that can be adequately covered by hard coding. It would be better to have an ExecutorManger instead of CompositeExecutor. If you have a reason for choosing the current design, I'd like to hear it.

2022-01-08 07:42 UTC, utam0k commented
If so, may it be difficult to separate `wasm-wasmer` feature?

2022-01-08 22:31 UTC, Furisto commented
@tsturzl @utam0k Instead of responding to individual comments I think it is better for me to explain what my current thinking around this feature is and where I want to go with this.

Quite a few webassembly runtimes exist nowadays with the most prominent ones being wasmer, wasmtime and wasmedge. These runtimes offer different features and make different tradeoffs (wasmedge for example currently does not support compiling .wat files while wasmer does). Therefore I plan to support different webassembly runtimes to accommodate different user requirements.  

It is likely that the current method of activating a handler using a feature flag will go away as I would like to avoid that everyone has to build youki with the appropriate configuration for their specific use case. Statically linking support for all webassembly runtimes would be problematic as this would bloat the size of the youki binary considerably (even with just wasmer the size of the binary roughly doubles) and would not be of use to anyone who is not wanting to run webassembly workloads (which is still the majority for the foreseeable future). Therefore dependencies will probably linked dynamically in the future. 

I am also thinking about allowing users to to specify the preferred order in which webassembly runtimes are asked to handle the workload in the config.json. It might even be possible that a configuration file located at a well known location can be provided that allows enables/disables certain handlers globally. This might be overkill though and we would want to check if other runtimes also plan to support such a feature.

Lastly one intended use case for this will be running hooks in a webassembly sandbox, so hooks will have to be adapted as well in the future.

What I want to say with this is: I would not focus to much on how exactly an executor is called because this is likely to change anyway. I would like to get this feature in first and then iterate on it with the knowledge gained from implementing support for further webassembly runtimes.

I welcome comments on the general direction of this feature.

2022-01-10 08:17 UTC, utam0k commented
> @tsturzl @utam0k Instead of responding to individual comments I think it is better for me to explain what my current thinking around this feature is and where I want to go with this.
> 
> Quite a few webassembly runtimes exist nowadays with the most prominent ones being wasmer, wasmtime and wasmedge. These runtimes offer different features and make different tradeoffs (wasmedge for example currently does not support compiling .wat files while wasmer does). Therefore I plan to support different webassembly runtimes to accommodate different user requirements.
> 
> It is likely that the current method of activating a handler using a feature flag will go away as I would like to avoid that everyone has to build youki with the appropriate configuration for their specific use case. Statically linking support for all webassembly runtimes would be problematic as this would bloat the size of the youki binary considerably (even with just wasmer the size of the binary roughly doubles) and would not be of use to anyone who is not wanting to run webassembly workloads (which is still the majority for the foreseeable future). Therefore dependencies will probably linked dynamically in the future.
> 
> I am also thinking about allowing users to to specify the preferred order in which webassembly runtimes are asked to handle the workload in the config.json. It might even be possible that a configuration file located at a well known location can be provided that allows enables/disables certain handlers globally. This might be overkill though and we would want to check if other runtimes also plan to support such a feature.
> 
> Lastly one intended use case for this will be running hooks in a webassembly sandbox, so hooks will have to be adapted as well in the future.
> 
> What I want to say with this is: I would not focus to much on how exactly an executor is called because this is likely to change anyway. I would like to get this feature in first and then iterate on it with the knowledge gained from implementing support for further webassembly runtimes.
> 
> I welcome comments on the general direction of this feature.

Great thoughts :100: 
I'm sorry if I'm understanding this wrong, but I think tsturzl is imagining this kind of code. I guess this should keep the byte size the same.
```rust
#[cfg(not(feature = "wasm-wasmer"))]
fn choose_executor() -> Result<Box<dyn Executor>> {
    Ok(Box::new(DefaultExecutor {}))
}

#[cfg(feature = "wasm-wasmer")]
fn choose_executor() -> Result<Box<dyn Executor>> {
    if true {
        Ok(Box::new(WasmerExecutor {}))
    } else {
        Ok(Box::new(DefaultExecutor {}))
    }
}
```

2022-01-19 22:37 UTC, Furisto commented
@utam0k @tsturzl PTAL

2022-01-22 06:43 UTC, utam0k approved these changes
LGTM
Thank you for accepting our suggestion!

2022-01-24 15:16 UTC, Furisto commented
@tsturzl seems to be busy, so I will go ahead and merge this now. But don't worry, there will be a new opportunity in the next PR for this.

2022-01-24 15:16 UTC, merged

2022-01-28 16:54 UTC, tsturzl commented
Apologies for my absence. I've been on-boarding new hires at work. I did take a brief look through, and thought this looked fine. I'm excited to see the feature get merged in. I may hack on it a bit on my free time to familiarize myself with the code base.