support configure cpu.idle by Cgroupfs
containers/youki pull request #908
Opened 2022-05-09 11:40 UTC by wineway

2022-05-09 12:13 UTC, utam0k commented on crates/libcontainer/Cargo.toml
> +oci-spec = { git = "https://github.com/containers/oci-spec-rs", rev = "6df620e" }
```suggestion
oci-spec = "0.5.6"
```

2022-05-09 12:13 UTC, utam0k commented on crates/youki/Cargo.toml
> +oci-spec = { git = "https://github.com/containers/oci-spec-rs", rev = "6df620e" }
```suggestion
oci-spec = "0.5.6"
```

2022-05-09 12:14 UTC, utam0k commented on crates/libcontainer/Cargo.toml
> +oci-spec = { git = "https://github.com/containers/oci-spec-rs", rev = "6df620e", features = ["proptests"] }
```suggestion
oci-spec = { version = "0.5.6", features = ["proptests"] }
```

2022-05-09 12:15 UTC, utam0k commented on crates/libcgroups/Cargo.toml
> +oci-spec = { git = "https://github.com/containers/oci-spec-rs", rev = "6df620e" }
```suggestion
oci-spec = "0.5.6"
```

2022-05-09 12:15 UTC, utam0k commented on crates/libcgroups/Cargo.toml
> +oci-spec = { git = "https://github.com/containers/oci-spec-rs", rev = "6df620e", features = ["proptests"] }
```suggestion
oci-spec = { version = "0.5.6", features = ["proptests"] }
```

2022-05-09 12:17 UTC, utam0k reviewed
@wineway Thanks for your first contribution. I left some comments. If you are okay, please add some integration tests? If you don't have time to add it, please tell me.
https://github.com/containers/youki/tree/main/tests/rust-integration-tests/integration_test/src/tests/cgroups/cpu

2022-05-09 20:50 UTC, tsturzl requested changes

2022-05-09 20:50 UTC, tsturzl commented on crates/libcgroups/src/v1/cpu.rs
> +                || cpu.idle().is_some()
Should either add or adapt the test cases to account for setting and checking this new setting.

2022-05-09 20:50 UTC, tsturzl commented on crates/libcgroups/src/v2/cpu.rs
> +            common::write_cgroup_file(path.join(CGROUP_CPU_IDLE), idle)?;
Same here. We should add or adapt the test cases to account for the new configuration.

2022-05-10 07:26 UTC, wineway commented
@utam0k @tsturzl updated! PTAL

2022-05-10 11:53 UTC, utam0k commented
> and seems tag 0.5.6 doesn't contains https://github.com/containers/oci-spec-rs/pull/103, so I edited commit messa

Oops, sorry, I failed to include your PR when I released oci-spec-rs 😭

2022-05-10 11:57 UTC, utam0k approved these changes
💯

2022-05-11 05:23 UTC, wineway commented
@utam0k Can you help trigger ci again? I don't have a cgroupv1 env, and I would like to ensure integration test is correct😂

2022-05-11 12:10 UTC, utam0k commented
@tsturzl Can I ask you to review it again?

2022-05-11 20:39 UTC, merged